### ISSUE TITLE
Voicemeter audio clipping

### ISSUE THREAD

**Issue by garaw7** [0xzer0x/athany-app#6] opened 2023-01-14 23:41 UTC
Hi I use voicemeeter as my audio interface and when i set it to the default sound device i get clipping in the audio. I tried changing the default audio device to speakers and it works. Only when the default device is my voicemeeter device i get crackles. I really need to fix this and would appreciate the help.

**Comment by 0xzer0x** [comment] 2023-01-15 06:40
As-salamu alaykum brother, It was an issue with the module used to play audio. It was fixed & tested on voicemeeter audio interface. If you're using the .py file directly you should preform a `git pull` & you're good to go.

Thanks for reporting the issue.

**Comment by 0xzer0x** [comment] 2023-01-17 15:22
As-salamu alaykum brother, we have recently released version 1.2.0, if the issue is fixed in this release, kindly close this issue on GitHub. In case the issue persists, please let us know.

**Closed as completed** 2023-01-19 05:54 UTC
